# Use the official Python image
FROM python:3.13-slim

ENV PORT=8080

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install the project into /app
COPY . /app
WORKDIR /app

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN uv sync --frozen

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE $PORT

# Run the FastMCP server
CMD ["uv", "run", "server"]
